"use client"

import { useEffect, useRef, useState } from "react"

export default function MermaidDiagram({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    let isMounted = true;

    async function renderDiagram() {
      if (!chart || !containerRef.current) return;
      
      try {
        const mermaid = (await import("mermaid")).default
        mermaid.initialize({
          startOnLoad: false,
          theme: "dark",
          themeVariables: {
            fontFamily: "Inter, system-ui, sans-serif",
            fontSize: "14px",
            primaryColor: "#1e3a5f",
            primaryTextColor: "#e2e8f0",
            primaryBorderColor: "#38bdf8",
            lineColor: "#64748b",
            secondaryColor: "#1e293b",
            tertiaryColor: "#0f172a",
          },
          securityLevel: "loose",
          flowchart: { htmlLabels: true, curve: "basis" },
        })

        // Allow both TD (Top-Down) and LR (Left-Right) charts natively as generated by the AI
        let cleanChart = chart;
        
        // Remove stray 'end' if there is no 'subgraph'
        if (!cleanChart.toLowerCase().includes('subgraph')) {
          cleanChart = cleanChart.replace(/\bend\b/gi, '');
        }
        
        // Reset container content and state before running mermaid
        if (containerRef.current) {
          containerRef.current.removeAttribute("data-processed");
          containerRef.current.innerHTML = cleanChart;
          
          await mermaid.run({
            nodes: [containerRef.current],
            suppressErrors: false,
          });
          
          if (isMounted) setError(false);
        }
      } catch (err) {
        console.error("Mermaid error:", err);
        if (isMounted) setError(true);
      }
    }

    renderDiagram();

    return () => {
      isMounted = false;
    };
  }, [chart]);

  if (error) {
    return (
      <div className="my-4 p-4 bg-amber-950/30 rounded-xl border border-amber-700/40">
        <div className="text-amber-400 text-xs mb-2">⚠️ Diyagram Görüntülenemiyor</div>
        <pre className="text-[10px] text-slate-400 font-mono whitespace-pre-wrap bg-slate-900/60 p-3 rounded-lg">{chart}</pre>
      </div>
    )
  }

  return (
    <div className="my-4 p-4 bg-slate-900/60 rounded-xl border border-sky-500/10 overflow-hidden relative group">
      <style>{`
        .mermaid-container svg {
          width: 100% !important;
          max-width: 900px !important;
          height: auto !important;
          display: block;
          margin: 0 auto;
        }
      `}</style>
      <div className="text-[10px] text-sky-400/60 uppercase tracking-wider mb-2 font-medium flex items-center gap-1.5">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
        Akış Şeması
      </div>
      
      <div className="w-full flex justify-center py-2 overflow-auto mermaid-container">
        <div ref={containerRef} className="mermaid transition-opacity duration-300">
          {chart}
        </div>
      </div>
    </div>
  )
}
